[project]
name = "mcp-tutorials"
version = "0.1.0"
description = "Tutorial examples and learning resources for Model Context Protocol (MCP)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
